name: Build and update anti-AD lists

on:
  workflow_run:
    workflows: [Update upstream]
    types: [completed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get source code from master
      uses: actions/checkout@v4
      with:
        ref: master
        path: master

    - name: Get source code from adlist-maker
      uses: actions/checkout@v4
      with:
        ref: adlist-maker
        path: adlist-maker

    - name: Build lists
      working-directory: adlist-maker
      run: |
        echo "Triggered by ${{ github.event_name }} event."
        /bin/bash ./scripts/build-list.sh

    - name: Commit and push
      run: |
        mv -f ./adlist-maker/adblock-for-dnsmasq.conf ./master/
        mv -f ./adlist-maker/anti-ad-* ./master/
        cd ./master
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action[bot]"
        git commit -am "Auto renew the anti-AD list."
        git push

  sync:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get source code from master
      uses: actions/checkout@v4
      with:
        ref: master
        path: master

    - name: Get source code from website
      uses: actions/checkout@v4
      with:
        #token: ${{ secrets.PERSON_TOKEN }}
        repository: privacy-protection-tools/anti-ad.github.io
        ref: master
        path: website

    - name: Install sing-box
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo curl -fsSL https://sing-box.app/gpg.key -o /etc/apt/keyrings/sagernet.asc
        sudo chmod a+r /etc/apt/keyrings/sagernet.asc
        echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/sagernet.asc] https://deb.sagernet.org/ * *" | sudo tee /etc/apt/sources.list.d/sagernet.list > /dev/null
        sudo apt-get update
        sudo apt-get install sing-box

    - name: Compile sing-box rule-set
      working-directory: master
      run: |
        sing-box rule-set convert --type adguard ./anti-ad-adguard.txt --output ./anti-ad-sing-box.srs
        echo '========================================'
        sha256sum ./anti-ad-sing-box.srs
        echo '========================================'

    - name: Update website lists
      run: |
        cat ./master/anti-ad-easylist.txt >./website/docs/easylist.txt
        cat ./master/anti-ad-easylist.txt.md5 >./website/docs/easylist.txt.md5
        cat ./master/anti-ad-adguard.txt >./website/docs/adguard.txt
        cat ./master/anti-ad-adguard.txt.md5 >./website/docs/adguard.txt.md5
        cat ./master/adblock-for-dnsmasq.conf >./website/docs/dnsmasq.conf
        cat ./master/adblock-for-dnsmasq.conf >./website/docs/anti-ad-for-dnsmasq.conf
        cat ./master/anti-ad-smartdns.conf >./website/docs/anti-ad-for-smartdns.conf
        cat ./master/anti-ad-surge.txt >./website/docs/surge.txt
        cat ./master/anti-ad-surge2.txt >./website/docs/surge2.txt
        cat ./master/anti-ad-clash.yaml >./website/docs/clash.yaml
        cat ./master/anti-ad-domains.txt >./website/docs/domains.txt
        cat ./master/anti-ad-sing-box.srs >./website/docs/anti-ad-sing-box.srs
        echo '========================================'
        ls -lha ./website/docs/

  #  - name: Commit and push
  #    working-directory: website
  #    run: |
  #      git config --global user.email "action@github.com"
  #      git config --global user.name "GitHub Action[bot]"
  #      git commit -am "Sync latest lists"
  #      git push
